### ISSUE TITLE
OpenGL rendering issue on Intel Iris driver

### ISSUE THREAD

**Issue by rfht** [rfht/fnaify#48]
Seen with FNA.dll 20.09, 20.08 (with and without FNA3D). Seen in pretty much all tested games: Apple Jack, Rogue Legacy, Chasm.

Setting `FNA3D_FORCE_DRIVER=Vulkan` doesn't have this problem.
Workarounds: 
`FNA3D_OPENGL_FORCE_ES3=1`
or
`FNA3D_OPENGL_FORCE_CORE_PROFILE=1`

Seen on Intel i7-10700.

This here appears to be the issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3431

```
=================================================================
    Managed Stacktrace:
=================================================================
     at <unknown> <0xffffffff>
     at Microsoft.Xna.Framework.Graphics.FNA3D:FNA3D_DrawIndexedPrimitives <0x000fe>
     at Microsoft.Xna.Framework.Graphics.GraphicsDevice:DrawIndexedPrimitives <0x000c2>
     at Microsoft.Xna.Framework.Graphics.SpriteBatch:DrawPrimitives <0x00232>
     at Microsoft.Xna.Framework.Graphics.SpriteBatch:PushSprite <0x0022a>
     at Microsoft.Xna.Framework.Graphics.SpriteBatch:Draw <0x002a2>
     at MyFirstGameTutorialSample1.Game1:Draw <0x0190a>
     at Microsoft.Xna.Framework.Game:Tick <0x0075a>
     at Microsoft.Xna.Framework.Game:RunLoop <0x0010a>
     at Microsoft.Xna.Framework.Game:Run <0x000e2>
     at MyFirstGameTutorialSample1.Program:Main <0x0008a>
     at <Module>:runtime_invoke_void_object <0x000b0>
=================================================================
```
```
(gdb) bt full
#0  thrkill () at /tmp/-:3
No locals.
#1  0x00000cd724a57aae in _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:51
        sa = {__sigaction_u = {__sa_handler = 0xcd6b86ada00, __sa_sigaction = 0xcd6b86ada00}, sa_mask = 4294919744, 
          sa_flags = 32639}
        mask = 4294967263
[...]
#5  <signal handler called>
No symbol table info available.
#6  0x00000cd71fcc8f07 in DebugCall (source=33350, type=33360, id=1, severity=33387, length=26, 
    message=0x7f7fffff4e60 "SIMD32 shader inefficient\n", userParam=0x0)
    at /usr/ports/pobj/fna3d-20.09/FNA/lib/FNA3D/src/FNA3D_Driver_OpenGL.c:5259
No locals.
#7  0x00000cd66ef565b0 in ?? () from /usr/X11R6/lib/modules/dri/iris_dri.so
No symbol table info available.
[...]
#19 0x00000cd66ef3190e in ?? () from /usr/X11R6/lib/modules/dri/iris_dri.so
No symbol table info available.
#20 0x00000cd71fcbd1fb in OPENGL_DrawIndexedPrimitives (driverData=0xcd6540e1750, 
    primitiveType=FNA3D_PRIMITIVETYPE_TRIANGLELIST, baseVertex=0, minVertexIndex=0, numVertices=4, startIndex=0, 
    primitiveCount=2, indices=0xcd743442820, indexElementSize=FNA3D_INDEXELEMENTSIZE_16BIT)
    at /usr/ports/pobj/fna3d-20.09/FNA/lib/FNA3D/src/FNA3D_Driver_OpenGL.c:1565
        tps = 0 '\000'
        renderer = 0xcd6540e1750
        buffer = 0xcd743442820
#21 0x00000cd71fcb8d5c in FNA3D_DrawIndexedPrimitives (device=0xcd707d3e400, 
    primitiveType=FNA3D_PRIMITIVETYPE_TRIANGLELIST, baseVertex=0, minVertexIndex=0, numVertices=4, startIndex=0, 
    primitiveCount=2, indices=0xcd743442820, indexElementSize=FNA3D_INDEXELEMENTSIZE_16BIT)
    at /usr/ports/pobj/fna3d-20.09/FNA/lib/FNA3D/src/FNA3D.c:260
[...]
```

**Comment by rfht** [comment]
Seems to be resolved on OpenBSD 7.0 or soon thereafter...
