### ISSUE TITLE
All games: Illegal Instruction, _dl_bind in backtrace

### ISSUE THREAD

**Issue by rfht** [rfht/fnaify#55]
need to get a trace or look at core file

**Comment by rfht** [comment]
this is actually present in all fnaify applications with dlopen being apparently at the core of the issue. First noticed on -current snapshot #151 from December 7th, 2021.

Sample backtrace from egdb with rogue legacy; have seen similar with CSteamworks in backtrace with Neurovoider:
```
#0  _dl_bind (object=0x2dae161b400, index=<optimized out>)
    at /usr/src/libexec/ld.so/amd64/rtld_machine.c:353
#1  0x000002da5383d28d in _dl_bind_start () at /usr/src/libexec/ld.so/amd64/ldasm.S:106
#2  0x000002db1c716dcd in SDL_InitDynamicAPI () from /usr/local/lib/libSDL2.so.0.10
#3  0x000002db1c7105f9 in SDL_GetPlatform_DEFAULT () from /usr/local/lib/libSDL2.so.0.10
```

**Comment by rfht** [comment]
(initially seen when trying Miasma 2)

**Comment by rfht** [comment]
Building a kernel with the following commit reverted fixes the issue (thanks brynet):

https://freshbsd.org/openbsd/src/commit/k7cI38x638E9zHVb

**Comment by rfht** [comment]
PS: I have reproduced this on another amd64 machine (Thinkpad X395; the other machine was the Dell Precision 7560)

**Comment by rfht** [comment]
This should be resolved with guenther@'s revert https://github.com/openbsd/src/commit/6ac18ccb9b6851970e60b23060d3f6908d265ecd
